package com.campus.hub.service;

import com.campus.hub.exception.EntityNotFoundException;
import com.campus.hub.dto.NotificationCreateRequest;
import com.campus.hub.entity.NotificationCategory;
import com.campus.hub.dto.AdminCreateUserRequest;
import com.campus.hub.dto.UserSummaryResponse;
import com.campus.hub.entity.CampusUser;
import com.campus.hub.entity.Role;
import com.campus.hub.repository.CampusUserRepository;
import java.util.List;
import java.util.Locale;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class UserManagementServiceImpl implements UserManagementService {

    private final CampusUserRepository campusUserRepository;
    private final PasswordEncoder passwordEncoder;
    private final NotificationService notificationService;

    public UserManagementServiceImpl(CampusUserRepository campusUserRepository, PasswordEncoder passwordEncoder, NotificationService notificationService) {
        this.campusUserRepository = campusUserRepository;
        this.passwordEncoder = passwordEncoder;
        this.notificationService = notificationService;
    }

    @Override
    @Transactional(readOnly = true)
    public List<UserSummaryResponse> getAllUsers() {
        return campusUserRepository.findAll()
                .stream()
                .map(this::toSummary)
                .toList();
    }

    @Override
    @Transactional
    public UserSummaryResponse createUser(AdminCreateUserRequest request) {
        // Changed to .getRole() from .role()
        Role role = request.getRole();
        if (role != Role.ADMIN && role != Role.TECHNICIAN && role != Role.SECURITY) {
            throw new IllegalArgumentException(
                    "Only ADMIN, TECHNICIAN, or SECURITY accounts can be created here. Regular users sign up on the public form.");
        }

        // Changed all record-style accessors to .get...()
        String normalizedEmail = normalizeEmail(request.getEmail());
        String normalizedName = normalizeName(request.getFullName());
        String normalizedUsername = normalizeUsername(request.getUsername());

        campusUserRepository.findByEmailIgnoreCase(normalizedEmail).ifPresent(u -> {
            throw new IllegalArgumentException("Email is already registered");
        });
        if (campusUserRepository.existsByUsernameIgnoreCase(normalizedUsername)) {
            throw new IllegalArgumentException("Username is already taken");
        }

        // Replaced .builder() with the full-args constructor implemented in your
        // CampusUser entity
        // Parameters: id, fullName, email, username, role, authProvider, passwordHash,
        // enabled, createdAt, updatedAt, lastLoginAt, profilePictureUrl
        CampusUser user = new CampusUser(
                null, // id (Generated by DB)
                normalizedName,
                normalizedEmail,
                normalizedUsername,
                role,
                "LOCAL",
                passwordEncoder.encode(request.getPassword()),
                true, // enabled
                null, // createdAt (Generated by Hibernate)
                null, // updatedAt (Generated by Hibernate)
                null, // lastLoginAt
                null // profilePictureUrl
        );

        CampusUser saved = campusUserRepository.save(user);
        return toSummary(saved);
    }

    @Override
    @Transactional
    public UserSummaryResponse updateRole(Long userId, Role role) {
        CampusUser user = campusUserRepository.findById(userId)
                .orElseThrow(() -> new EntityNotFoundException("User not found with id: " + userId));

        Role oldRole = user.getRole();
        user.setRole(role);
        CampusUser updated = campusUserRepository.save(user);

        // Record accessor updated: request constructor now uses values passed to it
        notificationService.create(new NotificationCreateRequest(
                user.getId(),
                "SPECIFIC",
                NotificationCategory.SYSTEM,
                "Security Update: Role Changed",
                String.format("Your account role has been updated from %s to %s by an administrator.", oldRole, role),
                "SECURITY",
                null));

        return toSummary(updated);
    }

    private UserSummaryResponse toSummary(CampusUser user) {
        return new UserSummaryResponse(
                user.getId(),
                user.getFullName(),
                user.getEmail(),
                user.getUsername(),
                user.getRole(),
                user.getAuthProvider(),
                user.isEnabled());
    }

    private String normalizeEmail(String email) {
        return email == null ? "" : email.trim().toLowerCase(Locale.ROOT);
    }

    private String normalizeName(String fullName) {
        String name = fullName == null ? "" : fullName.trim();
        if (name.isEmpty()) {
            throw new IllegalArgumentException("fullName is required");
        }
        return name;
    }

    private String normalizeUsername(String username) {
        if (username == null) {
            throw new IllegalArgumentException("username is required");
        }
        String normalized = username.trim().toLowerCase(Locale.ROOT);
        if (normalized.length() < 3) {
            throw new IllegalArgumentException("username must be at least 3 characters");
        }
        return normalized;
    }
}